area:
- -5.0
- 110.0
- -45.0
- 155.0
date: -1
date_format: '%Y%m%d'
look_back: 365
name: test
param:
- tp
save_dir: null
save_grib: false
save_netcdf: true
source: ecmwf
step:
- 3
stream: enfo
temp_filename: ./temp.grib
time:
- 0
- 12
type:
- pf
